using System.Collections.Generic;

namespace SipStack.Header
{
    public class HeaderDto
    {
        public IMethod Method { get; }
        public IReadOnlyList<string> Accept { get; set; }
        public IReadOnlyList<string> AcceptContact { get; set; }
        public IReadOnlyList<string> AcceptEncoding { get; set; }
        public IReadOnlyList<string> AcceptLanguage { get; set; }
        public IReadOnlyList<string> AcceptResourcePriority { get; set; }
        public IReadOnlyList<string> AlertInfo { get; set; }
        public IReadOnlyList<string> Allow { get; set; }
        public IReadOnlyList<string> AllowEvents { get; set; }
        public IReadOnlyList<string> AnswerMode { get; set; }
        public IReadOnlyList<string> AuthenticationInfo { get; set; }
        public IReadOnlyList<string> Authorization { get; set; }
        public IReadOnlyList<string> CallId { get; set; }
        public IReadOnlyList<string> CallInfo { get; set; }
        public IReadOnlyList<string> Contact { get; set; }
        public IReadOnlyList<string> ContentDisposition { get; set; }
        public IReadOnlyList<string> ContentEncoding { get; set; }
        public IReadOnlyList<string> ContentLanguage { get; set; }
        public int ContentLength { get; set; }
        public string ContentType { get; set; }
        public IReadOnlyList<string> Cseq { get; set; }
        public IReadOnlyList<string> Date { get; set; }
        public IReadOnlyList<string> Encryption { get; set; }
        public IReadOnlyList<string> ErrorInfo { get; set; }
        public IReadOnlyList<string> Event { get; set; }
        public IReadOnlyList<string> Expires { get; set; }
        public IReadOnlyList<string> FeatureCaps { get; set; }
        public IReadOnlyList<string> FlowTimer { get; set; }
        public IReadOnlyList<string> From { get; set; }
        public IReadOnlyList<string> Geolocation { get; set; }
        public IReadOnlyList<string> GeolocationError { get; set; }
        public IReadOnlyList<string> GeolocationRouting { get; set; }
        public IReadOnlyList<string> Hide { get; set; }
        public IReadOnlyList<string> HistoryInfo { get; set; }
        public IReadOnlyList<string> Identity { get; set; }
        public IReadOnlyList<string> IdentityInfo { get; set; }
        public IReadOnlyList<string> InfoPackage { get; set; }
        public IReadOnlyList<string> InReplyTo { get; set; }
        public IReadOnlyList<string> Join { get; set; }
        public IReadOnlyList<string> MaxBreadth { get; set; }
        public IReadOnlyList<string> MaxForwards { get; set; }
        public IReadOnlyList<string> MimeVersion { get; set; }
        public IReadOnlyList<string> MinExpires { get; set; }
        public IReadOnlyList<string> MinSe { get; set; }
        public IReadOnlyList<string> Organization { get; set; }
        public IReadOnlyList<string> PaccessNetworkInfo { get; set; }
        public IReadOnlyList<string> PanswerState { get; set; }
        public IReadOnlyList<string> PassertedIdentity { get; set; }
        public IReadOnlyList<string> PassertedService { get; set; }
        public IReadOnlyList<string> PassociatedUri { get; set; }
        public IReadOnlyList<string> PcalledPartyId { get; set; }
        public IReadOnlyList<string> PchargingFunctionAddresses { get; set; }
        public IReadOnlyList<string> PchargingVector { get; set; }
        public IReadOnlyList<string> PdcsTracePartyId { get; set; }
        public IReadOnlyList<string> PdcsOsps { get; set; }
        public IReadOnlyList<string> PdcsBillingInfo { get; set; }
        public IReadOnlyList<string> PdcsLaes { get; set; }
        public IReadOnlyList<string> PdcsRedirect { get; set; }
        public IReadOnlyList<string> PearlyMedia { get; set; }
        public IReadOnlyList<string> PmediaAuthorization { get; set; }
        public IReadOnlyList<string> PpreferredIdentity { get; set; }
        public IReadOnlyList<string> PpreferredService { get; set; }
        public IReadOnlyList<string> PprivateNetworkIndication { get; set; }
        public IReadOnlyList<string> PprofileKey { get; set; }
        public IReadOnlyList<string> PrefusedUriList { get; set; }
        public IReadOnlyList<string> PservedUser { get; set; }
        public IReadOnlyList<string> PuserDatabase { get; set; }
        public IReadOnlyList<string> PvisitedNetworkId { get; set; }
        public IReadOnlyList<string> Path { get; set; }
        public IReadOnlyList<string> PermissionMissing { get; set; }
        public IReadOnlyList<string> PolicyContact { get; set; }
        public IReadOnlyList<string> PolicyId { get; set; }
        public IReadOnlyList<string> Priority { get; set; }
        public IReadOnlyList<string> PrivAnswerMode { get; set; }
        public IReadOnlyList<string> Privacy { get; set; }
        public IReadOnlyList<string> ProxyAuthenticate { get; set; }
        public IReadOnlyList<string> ProxyAuthorization { get; set; }
        public IReadOnlyList<string> ProxyRequire { get; set; }
        public IReadOnlyList<string> Rack { get; set; }
        public IReadOnlyList<string> Reason { get; set; }
        public IReadOnlyList<string> ReasonPhrase { get; set; }
        public IReadOnlyList<string> RecordRoute { get; set; }
        public IReadOnlyList<string> RecvInfo { get; set; }
        public IReadOnlyList<string> ReferEventsAt { get; set; }
        public IReadOnlyList<string> ReferStub { get; set; }
        public IReadOnlyList<string> ReferTo { get; set; }
        public IReadOnlyList<string> ReferredBy { get; set; }
        public IReadOnlyList<string> RejectContact { get; set; }
        public IReadOnlyList<string> Replaces { get; set; }
        public IReadOnlyList<string> ReplyTo { get; set; }
        public IReadOnlyList<string> RequestDisposition { get; set; }
        public IReadOnlyList<string> Require { get; set; }
        public IReadOnlyList<string> ResourcePriority { get; set; }
        public IReadOnlyList<string> ResponseKey { get; set; }
        public IReadOnlyList<string> RetryAfter { get; set; }
        public IReadOnlyList<string> Route { get; set; }
        public IReadOnlyList<string> Rseq { get; set; }
        public IReadOnlyList<string> SecurityClient { get; set; }
        public IReadOnlyList<string> SecurityServer { get; set; }
        public IReadOnlyList<string> SecurityVerify { get; set; }
        public IReadOnlyList<string> Server { get; set; }
        public IReadOnlyList<string> ServiceRoute { get; set; }
        public IReadOnlyList<string> SessionExpires { get; set; }
        public IReadOnlyList<string> SessionId { get; set; }
        public IReadOnlyList<string> SipEtag { get; set; }
        public IReadOnlyList<string> SipIfMatch { get; set; }
        public IReadOnlyList<string> Subject { get; set; }
        public IReadOnlyList<string> SubscriptionState { get; set; }
        public IReadOnlyList<string> Supported { get; set; }
        public IReadOnlyList<string> SuppressIfMatch { get; set; }
        public IReadOnlyList<string> TargetDialog { get; set; }
        public IReadOnlyList<string> Timestamp { get; set; }
        public IReadOnlyList<string> To { get; set; }
        public IReadOnlyList<string> TriggerConstant { get; set; }
        public IReadOnlyList<string> Unsupported { get; set; }
        public IReadOnlyList<string> UserAgent { get; set; }
        public IReadOnlyList<string> UserToUser { get; set; }
        public IReadOnlyList<string> Via { get; set; }
        public IReadOnlyList<string> Warning { get; set; }
        public IReadOnlyList<string> WwwAuthenticate { get; set; }
    }
}
